
#pragma once

#define COLOR(A) "\e[" A "m"
#define COLOR2(A, B) "\e[" A ";" B "m"
#define COLOR3(A, B, C) "\e[" A ";" B ";" C "m"
#define COLOR4(A, B, C, D) "\e[" A ";" B ";" C ";" D "m"

#define RESET               "0"
#define BOLD                "1"
#define DIM                 "2"
#define UNDERLINE           "4"
#define BLINK               "5"
#define REVERSE             "7"
#define HIDDEN              "8"
#define RESET_BOLD          "21"
#define RESET_DIM           "22"
#define RESET_UNDERLINE     "24"
#define RESET_BLINK         "25"
#define RESET_REVERSE       "27"
#define RESET_HIDDEN        "28"
#define BLACK               "30"
#define RED                 "31"
#define GREEN               "32"
#define YELLOW              "33"
#define BLUE                "34"
#define MAGENTA             "35"
#define CYAN                "36"
#define LIGHT_GREY          "37"
#define DEFAULT             "39"
#define BG_BLACK            "40"
#define BG_RED              "41"
#define BG_GREEN            "42"
#define BG_YELLOW           "43"
#define BG_BLUE             "44"
#define BG_MAGENTA          "45"
#define BG_CYAN             "46"
#define BG_LIGHT_GREY       "47"
#define DARK_GREY           "90"
#define LIGHT_RED           "91"
#define LIGHT_GREEN         "92"
#define LIGHT_YELLOW        "93"
#define LIGHT_BLUE          "94"
#define LIGHT_MAGENTA       "95"
#define LIGHT_CYAN          "96"
#define WHITE               "97"
#define BG_DARK_GREY        "100"
#define BG_LIGHT_RED        "101"
#define BG_LIGHT_GREEN      "102"
#define BG_LIGHT_YELLOW     "103"
#define BG_LIGHT_BLUE       "104"
#define BG_LIGHT_MAGENTA    "105"
#define BG_LIGHT_CYAN       "106"
#define BG_WHITE            "107"
