
#include "./op.h"

#define TOKEN_OP(TOKEN, OP) [TOKEN_CLASS(TOKEN)] = TYPE_OP_NAME(OP)

const type_op_name table_match[TOKEN_CLASS(_)] = {
    TOKEN_OP(TILDE, REGEX),
    TOKEN_OP(EXCLAMATION, BOOL_NOT),
    TOKEN_OP(EXCLAMATION_COLON, BOOL_NOT_ASSIGN),
    TOKEN_OP(EXCLAMATION_EQUAL, BOOL_NOT_EQUAL),
    TOKEN_OP(EXCLAMATION_DOUBLE, BIT_NOT),
    TOKEN_OP(EXCLAMATION_DOUBLE_COLON, BIT_NOT_ASSIGN),
    TOKEN_OP(POUND, MATCH),
    TOKEN_OP(AT, LOOP),
    TOKEN_OP(DOLLAR, CAST),
    TOKEN_OP(PERCENT, MOD),
    TOKEN_OP(PERCENT_COLON, MOD_ASSIGN),
    TOKEN_OP(CARET, CATCH),
    TOKEN_OP(CARET_DOUBLE, BIT_XOR),
    TOKEN_OP(CARET_DOUBLE_COLON, BIT_XOR_ASSIGN),
    TOKEN_OP(AMPERSAND, BOOL_AND),
    TOKEN_OP(AMPERSAND_DOUBLE, BIT_AND),
    TOKEN_OP(AMPERSAND_DOUBLE_COLON, BIT_AND_ASSIGN),
    TOKEN_OP(STAR, MUL),
    TOKEN_OP(STAR_COLON, MUL_ASSIGN),
    TOKEN_OP(STAR_DOUBLE, EXP),
    TOKEN_OP(STAR_DOUBLE_COLON, EXP_ASSIGN),
    TOKEN_OP(DASH, SUB),
    TOKEN_OP(DASH_COLON, SUB_ASSIGN),
    TOKEN_OP(PLUS, ADD),
    TOKEN_OP(PLUS_COLON, ADD_ASSIGN),
    TOKEN_OP(EQUAL, BOOL_EQUAL),
    TOKEN_OP(EQUAL_DOUBLE, BOOL_DEEP_EQUAL),
    TOKEN_OP(PIPE, BOOL_OR),
    TOKEN_OP(PIPE_DOUBLE, BIT_OR),
    TOKEN_OP(PIPE_DOUBLE_COLON, BIT_OR_ASSIGN),
    TOKEN_OP(COLON, ASSIGN),
    TOKEN_OP(COLON_DOUBLE, SHADOW),
    TOKEN_OP(QUOTE, HAS),
    TOKEN_OP(ARROW_LEFT, BOOL_LESS),
    TOKEN_OP(ARROW_LEFT_COLON_ARROW_RIGHT, SWAP),
    TOKEN_OP(ARROW_LEFT_EQUAL, BOOL_LESS_EQUAL),
    TOKEN_OP(ARROW_LEFT_EQUAL_ARROW_RIGHT, COMPARE),
    TOKEN_OP(ARROW_LEFT_DOUBLE, BIT_LEFT_SHIFT),
    TOKEN_OP(ARROW_LEFT_DOUBLE_COLON, BIT_LEFT_SHIFT_ASSIGN),
    TOKEN_OP(ARROW_LEFT_TRIPLE, BIT_LEFT_SHIFT_ROTATE),
    TOKEN_OP(ARROW_LEFT_TRIPLE_COLON, BIT_LEFT_SHIFT_ROTATE_ASSIGN),
    TOKEN_OP(COMMA, CONCAT),
    TOKEN_OP(COMMA_COLON, CONCAT_ASSIGN),
    TOKEN_OP(ARROW_RIGHT, BOOL_GREATER),
    TOKEN_OP(ARROW_RIGHT_EQUAL, BOOL_GREATER_EQUAL),
    TOKEN_OP(ARROW_RIGHT_DOUBLE, BIT_RIGHT_SHIFT),
    TOKEN_OP(ARROW_RIGHT_DOUBLE_COLON, BIT_RIGHT_SHIFT_ASSIGN),
    TOKEN_OP(ARROW_RIGHT_TRIPLE, BIT_RIGHT_SHIFT_ROTATE),
    TOKEN_OP(ARROW_RIGHT_TRIPLE_COLON, BIT_RIGHT_SHIFT_ROTATE_ASSIGN),
    TOKEN_OP(PERIOD_DOUBLE, RANGE),
    TOKEN_OP(QUESTION, IF),
    TOKEN_OP(FOWARD_SLASH, DIV),
    TOKEN_OP(FOWARD_SLASH_COLON, DIV_ASSIGN),
};

type *parser_op(const token_slice *slice) {
    if (!table_match[slice->class])
        return nullptr;
    return namespace_op(table_match[slice->class], nullptr, nullptr, nullptr);
}
