
#include "./class.h"

static const char *class_strs[] = {
    "INVALID",
    "END",
    "SPACES",
    "TABS",
    "NEW_LINE",
    "SEMICOLON",
    "TYPE",
    "VAR",
    "UNUSED_VAR",
    "BASE",
    "TRUE_VALUE",
    "TRUE_CONST",
    "FALSE_VALUE",
    "FALSE_CONST",
    "INTEGER",
    "FLOAT",
    "STRING",
    "SYMBOL",
    "UNUSED_SYMBOL",
    "COMMAND",
    "APPLY_START",
    "APPLY_END",
    "DEFINE_START",
    "DEFINE_END",
    "LAMBDA_START",
    "LAMBDA_END",
    "TILDE",
    "EXCLAMATION",
    "EXCLAMATION_COLON",
    "EXCLAMATION_EQUAL",
    "EXCLAMATION_DOUBLE",
    "EXCLAMATION_DOUBLE_COLON",
    "POUND",
    "AT",
    "DOLLAR",
    "DOLLAR_COLON",
    "PERCENT",
    "PERCENT_COLON",
    "CARET",
    "CARET_DOUBLE",
    "CARET_DOUBLE_COLON",
    "AMPERSAND",
    "AMPERSAND_DOUBLE",
    "AMPERSAND_DOUBLE_COLON",
    "STAR",
    "STAR_COLON",
    "STAR_DOUBLE",
    "STAR_DOUBLE_COLON",
    "DASH",
    "DASH_COLON",
    "PLUS",
    "PLUS_COLON",
    "EQUAL",
    "EQUAL_DOUBLE",
    "PIPE",
    "PIPE_DOUBLE",
    "PIPE_DOUBLE_COLON",
    "COLON",
    "COLON_DOUBLE",
    "QUOTE",
    "ARROW_LEFT",
    "ARROW_LEFT_COLON_ARROW_RIGHT",
    "ARROW_LEFT_EQUAL",
    "ARROW_LEFT_EQUAL_ARROW_RIGHT",
    "ARROW_LEFT_DOUBLE",
    "ARROW_LEFT_DOUBLE_COLON",
    "COMMA",
    "COMMA_COLON",
    "ARROW_RIGHT",
    "ARROW_RIGHT_EQUAL",
    "ARROW_RIGHT_DOUBLE",
    "ARROW_RIGHT_DOUBLE_COLON",
    "PERIOD_DOUBLE",
    "QUESTION",
    "FOWARD_SLASH",
    "FOWARD_SLASH_COLON",
    "COMMENT_RANGE",
    "COMMENT_LINE",
    "_"
};

const char *token_class_str(token_class class) {
    if (class >= TOKEN_CLASS(_))
        return "INVALID TOKEN CLASS";
    return class_strs[class];
}
