
#include "./op_name.h"

static const char *op_name_strs[] = {
    "_",
    "CMD_IS_MAIN",
    "CMD_EXPORT",
    "CMD_IMPORT",
    "CMD_LOG",
    "CMD_DEBUG",
    "CMD_TYPE",
    "CMD_RETURN_TYPE",
    "CMD_COPY",
    "CMD_DISASSEMBLE",
    "CMD_AST",
    "CMD_IR",
    "CMD_CHAR",
    "CMD_BREAK",
    "CMD_CONTINUE",
    "CMD_BITMASK",
    "CMD_RETURN",
    "CMD_YEILD",
    "CMD_VALUE",
    "CMD_ERROR",
    "CMD_REGEX",
    "CMD_TEST",
    "CMD_EXIT",
    "INDEX",
    "REGEX",
    "MATCH",
    "LOOP",
    "CAST",
    "CATCH",
    "ASSIGN",
    "SHADOW",
    "HAS",
    "SWAP",
    "COMPARE",
    "CONCAT",
    "CONCAT_ASSIGN",
    "RANGE",
    "IF",
    "MOD",
    "MOD_ASSIGN",
    "MUL",
    "MUL_ASSIGN",
    "EXP",
    "EXP_ASSIGN",
    "SUB",
    "SUB_ASSIGN",
    "ADD",
    "ADD_ASSIGN",
    "DIV",
    "DIV_ASSIGN",
    "BOOL_NOT",
    "BOOL_NOT_ASSIGN",
    "BOOL_NOT_EQUAL",
    "BOOL_AND",
    "BOOL_EQUAL",
    "BOOL_DEEP_EQUAL",
    "BOOL_OR",
    "BOOL_LESS",
    "BOOL_LESS_EQUAL",
    "BOOL_GREATER",
    "BOOL_GREATER_EQUAL",
    "BIT_NOT",
    "BIT_NOT_ASSIGN",
    "BIT_XOR",
    "BIT_XOR_ASSIGN",
    "BIT_AND",
    "BIT_AND_ASSIGN",
    "BIT_OR",
    "BIT_OR_ASSIGN",
    "BIT_LEFT_SHIFT",
    "BIT_LEFT_SHIFT_ASSIGN",
    "BIT_LEFT_SHIFT_ROTATE",
    "BIT_LEFT_SHIFT_ROTATE_ASSIGN",
    "BIT_RIGHT_SHIFT",
    "BIT_RIGHT_SHIFT_ASSIGN",
    "BIT_RIGHT_SHIFT_ROTATE",
    "BIT_RIGHT_SHIFT_ROTATE_ASSIGN",
    "INVALID"
};

const char *type_op_name_str(type_op_name op_name) {
    if (op_name >= TYPE_OP_NAME(INVALID))
        return "INVALID OP";
    return op_name_strs[op_name];
}
